In [168]:
import pandas as pd

In [169]:
#leer el archivo Reporte de ventas por articulos MOD 2.xlsx como df
df = pd.read_excel('Reporte de ventas por articulos MOD 2.xlsx')

In [170]:
df

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
0,R124132,VIDRIO GLASS SAMSUNG A02S / A03 / A03 CORE / ...,90.0,120.80,3.569538e+05,2.955130e+05,3.571000e+05,Vidrio Glass
1,PI3017,Pilas Boton 3 V Philco 2032,70.0,32.20,7.391105e+04,2.295580e+05,7.395001e+04,Pila
2,D1014,"CABLE USB ONLY MOD48 / V8 / 3,1A BLANCO Y NEGR...",55.0,35.29,1.551573e+05,4.396850e+05,1.552000e+05,Cable
3,C6,Pin Carga Sam J7 pro / J7 prime / J5 prime / J...,54.0,1.17,1.382985e+05,1.214090e+12,1.420500e+05,Pin Carga
4,SE966,SERVICIO TECNICO REVISION Y PRESUPUESTO,54.0,12.42,6.536850e+05,5.263190e+11,6.537000e+05,Servicio Tecnico
...,...,...,...,...,...,...,...,...
1550,RC76393,BATERIA SAM A14 / A52 / S20 FE / A52S 100% Ori...,-1.0,-8.16,-2.699012e+04,NaN,-2.700000e+04,Bateria
1551,PE8818,Pendrive Kingston DataTraveler SE9 DTSE9H 32GB...,-2.0,-10.05,-1.598784e+04,NaN,-1.600000e+04,Pendrive
1552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Joystick
1553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Joystick
1554,NaN,NaN,6294.0,166296.86,1.294925e+08,NaN,1.308388e+08,Joystick

In [171]:
#pasar a str la columna nombre del producto y la columna categoria
df['Nombre del Producto'] = df['Nombre del Producto'].astype(str)
df['Categoria'] = df['Categoria'].astype(str)

In [172]:
#ver valores ocn la cadena case disco en la columan nombre del producto
df[df['Nombre del Producto'].str.contains('case disco', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
376,D8211,CASE DISCO 3.0 Seisa Tranparente Dn-k209,4.0,16.2,31980.399658,197431.0,32000.0,CASE DISCO 3.0 Seisa Tranparente Dn-k209

In [173]:
#agregar en la columna categoria la cadena 'Accesorio Disco' si la columna nombre del producto contiene la cadena 'case disco'
df.loc[df['Nombre del Producto'].str.contains('case disco', case=False), 'Categoria'] = 'Accesorio Disco'

In [174]:
#ver valores con la cadena analogico
df[df['Nombre del Producto'].str.contains('analogico', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
640,CO126,Analogico Nintendo Switch Joy-Con Joystick Rep...,2.0,9.24,59988.817169,649251.0,60000.0,Analogico Nintendo Switch Joy-Con Joystick Rep...
1161,CO1162,Grip Para Analogico Nintendo Switch Joy Con Y ...,1.0,3.77,7995.441781,212102.0,8000.0,Grip Para Analogico Nintendo Switch Joy Con Y ...

In [175]:
#agregar en la columna categoria la cadena 'Repuesto Joystick' si la columna nombre del producto contiene la cadena 'analogico'
df.loc[df['Nombre del Producto'].str.contains('analogico', case=False), 'Categoria'] = 'Repuesto Joystick'

In [176]:
#ver valores que tengna estricamente la cadena pad y su columna categoria tiene mas de dos palabra
df[(df['Nombre del Producto'].str.contains('pad', case=False)) & (df['Categoria'].str.contains(r'\b\w+\b \b\w+\b \b\w+\b', regex=True))]
#Cambiar la categoria de esas filas encontradas a Mousepad
df.loc[(df['Nombre del Producto'].str.contains('pad', case=False)) & (df['Categoria'].str.contains(r'\b\w+\b \b\w+\b \b\w+\b', regex=True)), 'Categoria'] = 'Mousepad'

In [177]:
#cambiar la categoria de las filas que contengan la cadena 'analogo' a 'Repuesto Joystick'
df.loc[df['Nombre del Producto'].str.contains('analogo', case=False), 'Categoria'] = 'Repuesto Joystick'

In [178]:
#ver valores con la cadena analogico
df[df['Nombre del Producto'].str.contains('analogico|analogo', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
354,CO6263,ANALOGO JOYSTICK REPUESTO PS4 PS5 XBOX ONE,4.0,9.28,144988.756393,1.580990e+11,146725.5,Repuesto Joystick
640,CO126,Analogico Nintendo Switch Joy-Con Joystick Rep...,2.0,9.24,59988.817169,6.492510e+05,60000.0,Repuesto Joystick
1161,CO1162,Grip Para Analogico Nintendo Switch Joy Con Y ...,1.0,3.77,7995.441781,2.121020e+05,8000.0,Repuesto Joystick

In [179]:
#ver valores con la cadena joystick
df[df['Nombre del Producto'].str.contains('joystick', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
121,C2512,JOYSTICK XBOX 360 / PC CON CABLE 52A NJX301,10.0,156.99,241310.074201,1.537310e+05,241500.0000,Joystick
165,CO6258,JOYSTICK INALAMBRICO SEISA SJ-913 COLORES PC /...,8.0,80.00,159903.200000,1.999000e+05,160000.0000,Joystick
166,C6239,Joystick Bluetooth Con Soporte para Celular Se...,8.0,72.71,153419.688196,2.110130e+05,153500.0000,Joystick
354,CO6263,ANALOGO JOYSTICK REPUESTO PS4 PS5 XBOX ONE,4.0,9.28,144988.756393,1.580990e+11,146725.5000,Repuesto Joystick
396,JOY-61020,JOYSTICK PLAYSTATION PS4 DUALSHOCK COLORES WB-6,4.0,121.24,224053.299600,1.848220e+05,224200.0000,Joystick
514,JOY-61012,JOYSTICK PLAYSTATION PS4 TIME CAMUFALDOS JOY-6...,3.0,71.76,132413.170400,1.845430e+05,132500.0000,Joystick
515,JO11389,JOYSTICK XBOX 360/PC/ANDROID INALAMBRICO + DON...,3.0,82.62,138300.038253,1.674140e+05,138400.0000,Joystick
516,JO113101,Joystick Redragon Inalambrico Harrow PRO G808-...,3.0,123.42,221550.661800,1.944590e+05,240125.0000,Joystick
517,R6116,Joystick Redragon Saturn G807 Windows/Ps3 negro,3.0,61.71,114825.330900,1.860930e+05,114900.0000,Joystick
640,CO126,Analogico Nintendo Switch Joy-Con Joystick Rep...,2.0,9.24,59988.817169,6.492510e+05,60000.0000,Repuesto Joystick
676,CO112,CABLE CARGA Y JUEGA JOYSTICK XBOX 360,2.0,8.42,14089.819977,1.673580e+05,14100.0000,Joystick
705,CO1084,Consola 400 EN 1 Con JOYSTICK 400 Juegos co1084,2.0,29.00,43964.910000,1.516240e+05,44000.0000,Consola
723,C6253,FILM MEMBRANA CONDUCTOR JOYSTICK PS4 JDM-040,2.0,5.48,14993.372294,2.736230e+05,15000.0000,FILM MEMBRANA CONDUCTOR JOYSTICK PS4 JDM-040
736,JO11384,JOYSTICK INALAMBRICO PS5 DUAL SENSE MIDNIGHT ...,2.0,199.66,342758.414384,1.716920e+05,343000.0000,Joystick
737,JO15667,JOYSTICK PS2 DUAL SHOCK NIPPON ALTO RENDIMIENT...,2.0,12.38,26485.020670,2.139550e+05,26500.0000,Joystick
738,JO15670,JOYSTICK PS3 INALAMBRICO NIPPON,2.0,26.00,46268.540000,1.779770e+05,46300.0000,Joystick
739,JO11392,JOYSTICK PS3 SIN MARCA COLORES JS3,2.0,16.72,31979.776701,1.912880e+05,32000.0000,Joystick
740,JO11390,JOYSTICK XBOX ONE SERIE S/X / PC ELECTRIC VOLT,2.0,188.36,329772.089041,1.750960e+05,330000.0000,Joystick
741,JO15656,JOYSTICK XBOX ONE SERIE S/X / PC SHOCK BLUE QA...,2.0,188.36,330672.093441,1.755740e+05,330900.0044,Joystick
743,JO11382,Joystick Inalambrico Bt / Nintendo Switch / PC...,2.0,27.38,51969.751256,1.898200e+05,52000.0000,Joystick
744,2741,Joystick PS3 Bluetooth Sony Dualshock 3 SIMIL O,2.0,20.10,32475.689498,1.814920e+05,36500.0000,Badeja SIM
745,CO6273,Joystick PS4 Bluetooth bateria recargable ROJO...,2.0,39.06,71952.746461,1.842320e+05,72000.0000,Joystick
746,R6115,Joystick Redragon Inalambrico Harrow G808 Pc -...,2.0,72.60,132912.154000,1.830960e+05,133000.0000,Joystick
1066,CO11261,CONSOLA 8 BITS CON JOYSTICK Y 800 JUEGOS QF-G4...,1.0,21.00,38474.590000,1.832330e+05,38500.0000,Consola
1100,CO6243,Consola Alien 16bits HDMI + 2 joysticks inalam...,1.0,34.53,53961.844350,1.562860e+05,54000.0000,Consola
1102,CO629061,Consola Xbox Series S 512gb Blanca Fornite Roc...,1.0,583.00,880199.570000,1.509990e+05,880905.0000,Consola
1159,C627,Gatillos Gamepad Joystick W11+ Para Celular Fr...,1.0,0.63,6499.237700,1.031650e+11,6500.0000,Joystick
1174,C6244,JOYSTICK ARCADE PS2 PS3 PC NJP308,1.0,24.80,44969.992000,1.813520e+05,45000.0000,Joystick
1175,JO11398,JOYSTICK INALAMBRICO 2.4G POR 2 UNIDADES EN 1 ...,1.0,19.80,35476.042000,1.791930e+05,35500.0000,Joystick
1176,C6224,JOYSTICK Inalambrico Recargable AITECH C6 con ...,1.0,3.77,164995.441781,4.376560e+11,165000.0000,Joystick
1177,JO15669,JOYSTICK PLAYSTATION PS4 DIBUJO / PERSONAJE WB-4,1.0,20.72,34974.929795,1.688190e+05,35000.0000,Joystick
1178,C6220,JOYSTICK PLAYSTATION PS4 ORIGINAL CAMUFLADO CU...,1.0,65.30,156420.990868,2.395630e+05,156500.0000,Joystick
1179,JO113108,JOYSTICK PS4 (S) INTER MIAMI MESSI,1.0,32.51,57960.662900,1.783070e+05,58000.0000,Joystick
1180,JO11391,JOYSTICK XBOX ONE SERIE S/X / PC GREEN,1.0,94.18,164886.044521,1.750960e+05,165000.0000,Joystick
1181,JO15657,JOYSTICK XBOX ONE SERIE S/X / PC PULSE RED QAU...,1.0,94.18,164886.044521,1.750960e+05,165000.0000,Joystick
1183,JO15672,Joystick 4 Gatillos Para Celular Con Cooler Se...,1.0,5.65,11493.162671,2.034400e+05,11500.0000,Joystick
1184,JO11395,Joystick Bluetooth Seisa PS4 SJ-4013B,1.0,24.50,42970.355000,1.754100e+05,43000.0000,Joystick
1185,JO11388,Joystick Gamepad Switch/Pc/Ps3/Android Inalamb...,1.0,21.47,34974.018151,1.629180e+05,35000.0000,Joystick
1186,C6250,Joystick PS4 Bluetooth SEISA SJ-4011B,1.0,20.10,43975.679000,2.188050e+05,44000.0000,Joystick
1187,7412,Joystick T-Dagger Aries PC T-TGP500 Con Cable ...,1.0,26.98,48267.354200,1.789220e+05,48300.0000,Joystick
1441,CO1129546,SOPORTE DE CARGADOR PARA PS5 JOYSTICK SND-463,1.0,9.27,16592.533300,1.790130e+05,16603.7500,SOPORTE DE CARGADOR PARA PS5 JOYSTICK SND-463
1540,CO11271,CONSOLA G7 GAME BOX 3.5 PLG CON JOYSTICK,0.0,0.00,0.000000,NaN,0.0000,Consola

In [180]:
#ver valores con la cadena joystick y su columna categoria sea diferente de 'Repuesto Joystick', 'joystick', 'consola'
df[(df['Nombre del Producto'].str.contains('joystick', case=False)) & (~df['Categoria'].str.contains('Repuesto Joystick|Joystick|Consola'))]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
723,C6253,FILM MEMBRANA CONDUCTOR JOYSTICK PS4 JDM-040,2.0,5.48,14993.372294,273623.0,15000.00,FILM MEMBRANA CONDUCTOR JOYSTICK PS4 JDM-040
744,2741,Joystick PS3 Bluetooth Sony Dualshock 3 SIMIL O,2.0,20.10,32475.689498,181492.0,36500.00,Badeja SIM
1441,CO1129546,SOPORTE DE CARGADOR PARA PS5 JOYSTICK SND-463,1.0,9.27,16592.533300,179013.0,16603.75,SOPORTE DE CARGADOR PARA PS5 JOYSTICK SND-463

In [181]:
#en esos valores cambiar su categoria a 'Repuesto Joystick' solo si tienen la cadena membrana y soporte
df.loc[(df['Nombre del Producto'].str.contains('joystick', case=False)) & (~df['Categoria'].str.contains('Repuesto Joystick|Joystick|Consola')) & (df['Nombre del Producto'].str.contains('membrana|soporte', case=False)), 'Categoria'] = 'Repuesto Joystick'

In [182]:
#ver valores con la cadena joystick y su cattegoria se igual a Badeja SIM
df[(df['Nombre del Producto'].str.contains('joystick', case=False)) & (df['Categoria'] == 'Badeja SIM')]
#cambiar su categoria a 'Joystick'
df.loc[(df['Nombre del Producto'].str.contains('joystick', case=False)) & (df['Categoria'] == 'Badeja SIM'), 'Categoria'] = 'Joystick'

In [183]:
#ver valores con la cadene enchufe
df[df['Nombre del Producto'].str.contains('enchufe', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
289,A7030,Adaptador Enchufes Universal Viajero Reforzado...,5.0,1.89,11497.720890,608366.0,11500.0,Adaptador
909,AD7046,ADAPTADOR INTERNATIONAL DIVERSOS ENCHUFES SS17...,1.0,2.20,5997.341039,272627.0,6000.0,Adaptador
1118,AS1522,ENCHUFE INTELIGENTE WIFI SMART PLUG SA-014 GB,1.0,7.53,18990.883562,252224.0,19000.0,ENCHUFE INTELIGENTE WIFI SMART PLUG SA-014 GB
1258,LU9847,Mini Bola Led Rgb Led Party Light Enchufe A 22...,1.0,6.65,11991.954743,180351.0,12000.0,Luces

In [184]:
#Cambiar la categoria de los productos a 'Asistente Virtual' para los productos que tengan en su nombre la cadaena enchufe inteligente
df.loc[df['Nombre del Producto'].str.contains('enchufe inteligente', case=False), 'Categoria'] = 'Asistente Virtual'

In [185]:
#ver valores con la cadena tv
df[df['Nombre del Producto'].str.contains('tv', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
80,TV10915,Chromecast Google Tv HD 8gb Blanco Con Control...,13.0,715.00,1.216635e+06,1.701800e+05,1.217500e+06,Herramienta
111,CA712086,TRANSFORMADOR FUENTE TIRA DE LED CCTV CAMARAS ...,11.0,38.83,9.995304e+04,2.574330e+05,1.000000e+05,Herramienta
225,S9310,SOPORTE TV FIJO 26 A 55 DINAX DX-STVF2655,7.0,32.97,6.646358e+04,2.015990e+05,6.650000e+04,Soporte
277,SO11018,SOPORTE TV MOVIL CON BRAZO 26 A 55 SEISA GJ-CP303,6.0,81.00,1.664027e+05,2.054560e+05,1.665007e+05,Soporte
339,SO11019,SOPORTE TV FIJO 14 A 42 DELHIP DL-FJ1442,5.0,22.25,3.597541e+04,1.616980e+05,3.600000e+04,Soporte
440,TVS-ARM2-30-60I,SOPORTE TV DOBLE BRAZO MOVIL GLOBAL 30 A 60 IN...,4.0,69.80,2.375155e+05,3.653730e+05,2.551000e+05,Soporte
591,SO1101559,"SOPORTE TV FIJO SEISA 42 A 85"" HASTA 100KG/ Co...",3.0,48.96,1.169407e+05,2.388710e+05,1.170000e+05,Soporte
678,CA74191,CABLE HDMI A VGA 1.5M MALLADO HDTV TO VGA,2.0,5.00,1.379395e+04,2.759000e+05,1.380000e+04,Cable
858,SO11014,SOPORTE LCD BRAZO DOBLE 26 A 55 DINAX DX-SM2655TV,2.0,53.18,8.493565e+04,1.808890e+05,9.625000e+04,Soporte
867,TV15112,TV BOX MXQ-4K (1GB+8GB) Peiso,2.0,38.92,1.079529e+05,2.773920e+05,1.080000e+05,TV BOX MXQ-4K (1GB+8GB) Peiso
1023,PA131144,Barra Sonido Tv o Pc Bluetooth / Sd / Radio / ...,1.0,53.18,9.693565e+04,1.822990e+05,9.700000e+04,Parlante
1260,P635,Mini Teclado Only Smart Tv Bluetooth Retroilum...,1.0,1.00,1.829878e+04,1.829900e+10,1.830000e+04,Teclado
1470,TV10917,TV BOX (2G+16G) TX100,1.0,47.31,8.494275e+04,1.795660e+05,8.500000e+04,TV BOX (2G+16G) TX100
1471,TV10918,TV BOX T96D (2G+16G),1.0,45.17,8.744534e+04,1.936130e+05,8.750000e+04,TV BOX T96D (2G+16G)
1529,TV7618,Xiaomi Mi Tv Stick 4k Ram 2gb 8gb Android Tv,1.0,57.13,9.943087e+04,1.740640e+05,9.950000e+04,Xiaomi Mi Tv Stick 4k Ram 2gb 8gb Android Tv
1541,TV10919,CONVERTIDOR TV STICK 2GB 16GB ANDROID 10 SYSTE...,0.0,0.00,0.000000e+00,NaN,0.000000e+00,CONVERTIDOR TV STICK 2GB 16GB ANDROID 10 SYSTE...
1548,CO11264,XMI GAME BOX EMULADOR 10MIL JUEGOS 64GB + AND...,0.0,0.00,0.000000e+00,NaN,0.000000e+00,XMI GAME BOX EMULADOR 10MIL JUEGOS 64GB + AND...

In [186]:
#ver valores con la cadena tv y que su categoria sea distinta de la cadena: Herramienta, Soporte, Cable, Teclado y Parlante
df[(df['Nombre del Producto'].str.contains('tv', case=False)) & (~df['Categoria'].str.contains('Herramienta|Soporte|Cable|Teclado|Parlante'))]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
867,TV15112,TV BOX MXQ-4K (1GB+8GB) Peiso,2.0,38.92,107952.898402,277392.0,108000.0,TV BOX MXQ-4K (1GB+8GB) Peiso
1470,TV10917,TV BOX (2G+16G) TX100,1.0,47.31,84942.754900,179566.0,85000.0,TV BOX (2G+16G) TX100
1471,TV10918,TV BOX T96D (2G+16G),1.0,45.17,87445.344300,193613.0,87500.0,TV BOX T96D (2G+16G)
1529,TV7618,Xiaomi Mi Tv Stick 4k Ram 2gb 8gb Android Tv,1.0,57.13,99430.867009,174064.0,99500.0,Xiaomi Mi Tv Stick 4k Ram 2gb 8gb Android Tv
1541,TV10919,CONVERTIDOR TV STICK 2GB 16GB ANDROID 10 SYSTE...,0.0,0.00,0.000000,NaN,0.0,CONVERTIDOR TV STICK 2GB 16GB ANDROID 10 SYSTE...
1548,CO11264,XMI GAME BOX EMULADOR 10MIL JUEGOS 64GB + AND...,0.0,0.00,0.000000,NaN,0.0,XMI GAME BOX EMULADOR 10MIL JUEGOS 64GB + AND...

In [187]:
#A esos valores cambiar su categoria a 'TV Box'
df.loc[(df['Nombre del Producto'].str.contains('tv', case=False)) & (~df['Categoria'].str.contains('Herramienta|Soporte|Cable|Teclado|Parlante')), 'Categoria'] = 'TV Box'

In [188]:
#ver valores con la cadena sillon
df[df['Nombre del Producto'].str.contains('sillon', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
1427,SA1356,SILLON MASAJEADOR SUONO 174881,1.0,14.99,19983.439506,133322.0,20000.0,SILLON MASAJEADOR SUONO 174881

In [189]:
#cambiar categoria a 'Salud' para los productos que tengan en su nombre la cadena sillon
df.loc[df['Nombre del Producto'].str.contains('sillon', case=False), 'Categoria'] = 'Salud'

In [190]:
#ver valores con la cadena tostadora
df[df['Nombre del Producto'].str.contains('tostadora', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
1467,EL6715,TOSTADORA ELECTRICA ATMA DISNEY TOAT39DN - Mic...,1.0,27.23,45967.0517,168831.0,46000.0,TOSTADORA ELECTRICA ATMA DISNEY TOAT39DN - Mic...

In [191]:
#cambiar categoria a 'Electrodomesticos' para los productos que tengan en su nombre la cadena tostadora
df.loc[df['Nombre del Producto'].str.contains('tostadora', case=False), 'Categoria'] = 'Electrodomesticos'

In [192]:
#ver valores con la cadena wifi
df[df['Nombre del Producto'].str.contains('wifi', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
270,CO953,PLACA USB/WIFI 150M CON ANTENA 5DBI DNW150U2,6.0,30.00,56766.850000,189233.0,56800.0000,PLACA USB/WIFI 150M CON ANTENA 5DBI DNW150U2
434,CO8138,Receptor USB NANO Wireless WIFI AC600 Dual ban...,4.0,72.00,129820.440000,180317.0,129900.0000,Receptor
467,C8114,Antena Externa Adaptador Usb Wifi Placa Red La...,3.0,11.88,28485.641610,239799.0,28500.0000,Antena Externa Adaptador Usb Wifi Placa Red La...
533,C8118,Mini Adaptador USB Wifi tp-link TL-WN823N 300M...,3.0,35.37,62960.924550,178017.0,63000.0084,Adaptador
569,CO952,PLACA USB/WIFI 150M CON ANTENA DN-W150U3 or 13...,3.0,15.00,28483.435900,189900.0,28500.0109,PLACA USB/WIFI 150M CON ANTENA DN-W150U3 or 13...
698,CA11447,Camara De Seguridad Exterior Imou Bullet 2c 10...,2.0,62.00,119924.980000,193448.0,120000.0000,Camara de Seguridad
699,CA11438,Camara De Seguridad IPC-ZAS05 DOBLE LENTE 360 ...,2.0,83.56,149898.883505,201851.0,168750.0000,Camara de Seguridad
701,CA7431,Camara wifi Ezviz interior inteligente - C6N 1...,2.0,71.58,131513.393836,183750.0,131600.0000,Camara de Seguridad
848,CO957,RECEPTOR WIFI DINAX DOBLE BANDA 1300MBPS / DXR...,2.0,29.18,47767.756100,163711.0,47800.0000,Receptor
851,CO946,ROUTER DINAX WIFI 4 ANTENAS IEEE 802.11N DX-7R...,2.0,22.60,58972.650685,260962.0,59000.0000,Router
951,NG-Uw06,Adaptador Inalambrico Wifi Usb Red Noga NG-Uw0...,1.0,4.33,8995.216928,207752.0,9000.0040,Adaptador Inalambrico Wifi Usb Red Noga NG-Uw0...
1043,CA11440,CAMARA DE SEGURIDAD IP WIFI SUONO VISION NOCTU...,1.0,23.40,38971.685862,166567.0,39000.0000,Camara de Seguridad
1044,CA11436,CAMARA EXTERIOR IP WIFI IMOU Cruiser Se+ 4mp F...,1.0,65.99,118920.155194,180230.0,119000.0000,Camara de Seguridad
1083,CA11445,Camara De Seguridad Ezviz Domo Color Full H8C ...,1.0,46.00,89944.340000,195552.0,90000.0000,Camara de Seguridad
1084,CA11439,Camara De Seguridad IPC-ZAS06 DOBLE LENTE Domo...,1.0,68.37,118917.268322,173953.0,119000.0000,Camara de Seguridad
1086,CA11432,Camara Mini Espia De Seguridad Wifi Hd Con Mic...,1.0,14.44,29382.526826,203501.0,29400.0000,Camara de Seguridad
1118,AS1522,ENCHUFE INTELIGENTE WIFI SMART PLUG SA-014 GB,1.0,7.53,18990.883562,252224.0,19000.0000,Asistente Virtual
1127,CO95761,EXTENSOR DE RANGO De Wifi 300mbps 2.4ghz REP-R...,1.0,5.65,15993.755993,283086.0,16000.0000,Extensor Wifi
1212,LU8050,Lamparita Smart Nexxt RGB Wifi 220V Dicroiica x3,1.0,18.84,27979.186644,148520.0,28000.0000,Luces
1410,CO954,RECEPTOR 2.4G WIFI+BLUETOOTH 4.2 BT-165,1.0,8.12,14490.174800,178471.0,14500.0000,Receptor
1417,CO958,REPETIDOR WIFI 2 ANTENAS DINAX / REPRP4200C,1.0,14.81,26983.634950,182209.0,27000.0000,Extensor Wifi
1455,HE89285,Stencil Welsolo VS01 - ANDROID BT WIFI RF UNIV...,1.0,4.14,7144.213556,172586.0,7149.2200,Herramienta
1468,HE18511,TRINO MICROSCOPIO WIFIX WF-M50XT / 50X ZOOM / ...,1.0,436.48,646417.689600,148108.0,646900.0000,Herramienta

In [193]:
#cambiar categoria a 'Conectividad' para los productos que tengan en su nombre la cadena wifi y qeu su categoria sea distinta de : Herramienta, Asistente Virtual, Luces, Adaptador y Router
df.loc[(df['Nombre del Producto'].str.contains('wifi', case=False)) & (~df['Categoria'].str.contains('Herramienta|Asistente Virtual|Luces|Adaptador|Router')), 'Categoria'] = 'Conectividad'

In [194]:
#cambiar categoria a 'Conectividad' para los productos que tengan en su nombre la cadena adaptador inalambrico wifi
df.loc[df['Nombre del Producto'].str.contains('adaptador inalambrico wifi', case=False), 'Categoria'] = 'Conectividad'

In [195]:
#ver valores con la cadena extensor
df[df['Nombre del Producto'].str.contains('extensor', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
203,CA74155,Cable Extensor Usb 2.0 Macho A Macho Con Filtr...,7.0,23.92,48371.073702,202241.0,48400.00320,Cable
387,CO949,EXTENSOR / REPETIDOR KANJI KJN-RP4200B 4 ANTENAS,4.0,52.72,101941.717753,193375.0,101999.99515,Extensor Wifi
714,CO950,EXTENSOR / REPETIDOR KANJI KJN-RP4200A,2.0,20.34,33977.521575,167058.0,34000.00000,Extensor Wifi
715,EXTRE200,EXTENSOR DE RANGO Tp-Link Re200 Dual Band 2.4G...,2.0,52.20,90742.319000,173846.0,90800.00000,Extensor Wifi
1126,AD2110,EXTENSOR DE HDMI POR UTP RED ETHERNET 30M GM57...,1.0,4.18,7494.940377,179326.0,7500.00000,Adaptador
1127,CO95761,EXTENSOR DE RANGO De Wifi 300mbps 2.4ghz REP-R...,1.0,5.65,15993.755993,283086.0,16000.00000,Conectividad

In [196]:
#cambiar su cateogira a 'Conectividad'
df.loc[df['Categoria'] == 'Extensor Wifi', 'Categoria'] = 'Conectividad'

In [197]:
#ver valores con la cadena apolo
df[df['Nombre del Producto'].str.contains('apollo', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
912,H89161,APOLLO QIANLI,1.0,98.81,219890.81495,222550.0,220000.0,APOLLO QIANLI

In [198]:
#cambiar su categoria a 'Herramienta' para los productos que tengan en su nombre la cadena apollo
df.loc[df['Nombre del Producto'].str.contains('apollo', case=False), 'Categoria'] = 'Herramienta'

In [199]:
#ver valores con la cadena cubre
df[df['Nombre del Producto'].str.contains('cubre', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
202,CO11260,CUBRE DEDOS X2 PUBG COD MOBILE FREEFIRE ANTI-S...,7.0,4.33,12594.7607,290893.0,12600.0,CUBRE DEDOS X2 PUBG COD MOBILE FREEFIRE ANTI-S...

In [200]:
#cambiar la cattegoria de ese producto a Accesorio Gamer
df.loc[df['Nombre del Producto'].str.contains('cubre', case=False), 'Categoria'] = 'Accesorio Gamer'

In [201]:
#ver valores con la cadena zapatilla
df[df['Nombre del Producto'].str.contains('zapatilla', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
1530,EL877,Zapatilla Binorma 5 Bocas cable 1.5 Mtrs c/lla...,1.0,4.08,6995.061929,171469.0,7000.0,Zapatilla Binorma 5 Bocas cable 1.5 Mtrs c/lla...

In [202]:
#cambiar la categoria de esos productos a 'Electricidad'
df.loc[df['Nombre del Producto'].str.contains('zapatilla', case=False), 'Categoria'] = 'Electricidad'

In [203]:
#cambiar la categoria a Herramienta para los productos que tengan las siguientes cadenas: mascara uv
df.loc[df['Nombre del Producto'].str.contains('mascara uv', case=False), 'Categoria'] = 'Herramienta'

In [204]:
#Cambiar la categoria de los produtos con la cadena balanza
df.loc[df['Nombre del Producto'].str.contains('balanza', case=False), 'Categoria'] = 'Accesorio'

In [205]:
#ver valores con la cadena balanza
df[df['Nombre del Producto'].str.contains('balanza', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
645,A1003,BALANZA MINI DIGITAL DE PRECISION 500G / 0.1G ...,2.0,7.54,15590.883562,206797.0,15600.0,Accesorio

In [206]:
#cambiar categoria a 'Adaptador' de los productos que tengan en su cadena placa de sonido
df.loc[df['Nombre del Producto'].str.contains('placa de sonido', case=False), 'Categoria'] = 'Adaptador'

In [207]:
#cambiar categoria a 'Conectividad' de los productos que tengan en su caden placa de red
df.loc[df['Nombre del Producto'].str.contains('placa de red', case=False), 'Categoria'] = 'Conectividad'

In [208]:
#ver valores con la categoria disco
df[df['Categoria'].str.contains('Disco')]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
164,SSD480KIN,Disco Solido SSD 480GB KINGSTON A400 SATAIII 2.5,8.0,366.40,599495.126050,168438.0,617524.99805,Disco
376,D8211,CASE DISCO 3.0 Seisa Tranparente Dn-k209,4.0,16.20,31980.399658,197431.0,32000.00000,Accesorio Disco
383,SSD240KIN,Disco Solido SSD 240GB KINGSTON A400 SATAIII 2.5,4.0,120.56,200766.794521,166539.0,200900.00000,Disco
494,DI1244,"Disco Solido SSD 128GB PATRIOT P220 2.5"" SATA",3.0,49.65,121945.136750,245620.0,122000.00000,Disco
495,DI829215,Disco Solido SSD 1TB PATRIOT P210 Sata,3.0,222.27,359254.402397,161640.0,359500.00000,Disco
496,DI1239,Disco Solido SSD 480GB ADATA SU630 Sata,3.0,120.54,197866.794521,164161.0,198000.00000,Disco
673,AD2145,"CABLE ADAPTADOR DISCO SATA EXTERNO A USB 3,0 /...",2.0,13.48,24385.104600,180909.0,24400.00000,Disco
694,09-038,Cable USB a USB 3.0 Disco Externo Cable 1 Metr...,2.0,7.52,14890.905200,198038.0,14900.00440,Disco
707,DI1169,Disco Externo Toshiba Canvio 2tb Black Usb 3.0...,2.0,211.94,324765.806300,153245.0,325000.00000,Disco
708,DI1238,Disco Solido SSD 240GB ADATA SU630 Sata,2.0,48.98,96945.881187,197940.0,97000.00000,Disco
709,DI1234,Disco Solido SSD 512GB VERBATIM SATA 3,2.0,65.92,108927.155827,165252.0,109000.00000,Disco
854,SE5315,SERVICIO TECNICO NOTE INSTALACION DISCO,2.0,0.00,20.000000,NaN,20.00000,Disco
1078,TR-1005,Cable Sata Power Molex Discos Rigidos 4 Pin No...,1.0,0.31,2499.620148,806352.0,2500.00000,Disco
1109,DI1246,"DISCO SSD SOLIDO PNY 480GB 2.5"" SATA CS900",1.0,39.78,84956.043100,266994.0,106250.00000,Disco
1112,DI1235,Disco Solido SSD 120Gb GIGABYTE Sata,1.0,20.09,30777.799087,153210.0,30800.00000,Disco
1113,DI8233,Disco Solido SSD 1TB PNY 1TB-RB SATA,1.0,64.67,119928.540811,185457.0,120000.00000,Disco
1114,DI8226,Disco Solido SSD 250GB Kingston NV1 SNVS/250G,1.0,38.93,51456.985731,132189.0,51500.00000,Disco
1115,DI1242,Disco Solido SSD 256GB PATRIOT P210 SATA3 2.5,1.0,22.83,37974.772850,166348.0,38000.00000,Disco
1116,DI1243,Disco Solido SSD 256GB PATRIOT P220 SATA3 2.5,1.0,19.40,29725.562243,153235.0,29747.00000,Disco
1117,DI8229,Disco Solido SSD 500GB M.2 NVME WESTERN DIGITA...,1.0,40.21,73455.563485,182690.0,73500.00000,Disco

In [209]:
#ver valores que tengan al mens las siguientes dos cadenas disco y cable
df[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('cable', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
135,DI11610,CARCASA EXTERNA PARA DISCO RIGIDO 2.5 CON CABL...,9.0,66.60,115726.406550,173774.0,115799.99955,Accesorio notebook
673,AD2145,"CABLE ADAPTADOR DISCO SATA EXTERNO A USB 3,0 /...",2.0,13.48,24385.104600,180909.0,24400.00000,Disco
694,09-038,Cable USB a USB 3.0 Disco Externo Cable 1 Metr...,2.0,7.52,14890.905200,198038.0,14900.00440,Disco
1078,TR-1005,Cable Sata Power Molex Discos Rigidos 4 Pin No...,1.0,0.31,2499.620148,806352.0,2500.00000,Disco

In [210]:
#ver valores con la cadena carcasa
df[df['Nombre del Producto'].str.contains('carcasa', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
135,DI11610,CARCASA EXTERNA PARA DISCO RIGIDO 2.5 CON CABL...,9.0,66.6,115726.40655,173774.0,115799.99955,Accesorio notebook

In [211]:
#cambiar la categoria de ese producto a 'Disco externo'
df.loc[df['Nombre del Producto'].str.contains('carcasa', case=False), 'Categoria'] = 'Disco Externo'

In [212]:
#ver valores con las siguientes dos cadenas estrictamente: disco y externo y que no tengan la cadena cable
df[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('externo', case=False) & ~df['Nombre del Producto'].str.contains('cable', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
707,DI1169,Disco Externo Toshiba Canvio 2tb Black Usb 3.0...,2.0,211.94,324765.8063,153245.0,325000.0,Disco

In [213]:
#A este valor cmabiar su categoria a Discos Externo
df.loc[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('externo', case=False) & ~df['Nombre del Producto'].str.contains('cable', case=False), 'Categoria'] = 'Disco Externo'

In [214]:
#ver valores que tengan estrictamente las siguientes dos cadenas: disco y cable
df[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('cable', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
135,DI11610,CARCASA EXTERNA PARA DISCO RIGIDO 2.5 CON CABL...,9.0,66.60,115726.406550,173774.0,115799.99955,Disco Externo
673,AD2145,"CABLE ADAPTADOR DISCO SATA EXTERNO A USB 3,0 /...",2.0,13.48,24385.104600,180909.0,24400.00000,Disco
694,09-038,Cable USB a USB 3.0 Disco Externo Cable 1 Metr...,2.0,7.52,14890.905200,198038.0,14900.00440,Disco
1078,TR-1005,Cable Sata Power Molex Discos Rigidos 4 Pin No...,1.0,0.31,2499.620148,806352.0,2500.00000,Disco

In [215]:
#de estos valores cambiar su categoria a 'Cable' si ademas no tienen la cadena Carcasa
df.loc[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('cable', case=False) & ~df['Nombre del Producto'].str.contains('carcasa', case=False), 'Categoria'] = 'Cable'

In [216]:
#ver valores que tengan estrictamente la cadena disco y servicio tecnico
df[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('servicio tecnico', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
854,SE5315,SERVICIO TECNICO NOTE INSTALACION DISCO,2.0,0.0,20.0,NaN,20.0,Disco

In [217]:
#de esos valores cambiar su categoria a 'Servicio Tecnico'
df.loc[df['Nombre del Producto'].str.contains('disco', case=False) & df['Nombre del Producto'].str.contains('servicio tecnico', case=False), 'Categoria'] = 'Servicio Tecnico'

In [218]:
#ver valores con la cadena ajedrez
df[df['Nombre del Producto'].str.contains('ajedrez', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
742,JU998,JUEGO DE AJEDREZ TABLERO MAGNETICO 3881A,2.0,15.4,27781.366,180419.0,27800.0,JUEGO DE AJEDREZ TABLERO MAGNETICO 3881A

In [219]:
#cambiar ese producto  a 'Juguete'
df.loc[df['Nombre del Producto'].str.contains('ajedrez', case=False), 'Categoria'] = 'Juguete'

In [220]:
#ver valores con la cadena hd externo
df[df['Nombre del Producto'].str.contains('hd externo', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
732,DI8228,HD EXTERNO 1TB PORTABLE WD ELEMENTS BLACK USB ...,2.0,141.44,217843.70445,154029.0,217999.99565,HD EXTERNO 1TB PORTABLE WD ELEMENTS BLACK USB ...

In [221]:
#cambiar la categoria de ese producto a 'Disco Externo'
df.loc[df['Nombre del Producto'].str.contains('hd externo', case=False), 'Categoria'] = 'Disco Externo'

In [222]:
#ve valores con la cadena bluetooth auto
df[df['Nombre del Producto'].str.contains('bluetooth auto', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
600,AC7268,Transmisor Inalambrico Bluetooth Auto Manos Li...,3.0,11.31,26986.325342,238627.0,27000.0,Transmisor Inalambrico Bluetooth Auto Manos Li...

In [223]:
#cambiar la categoria de ese producto a 'Accesorio'
df.loc[df['Nombre del Producto'].str.contains('bluetooth auto', case=False), 'Categoria'] = 'Accesorio'

In [224]:
#ver valores con la cadena cabezal
df[df['Nombre del Producto'].str.contains('cabezal', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
58,CA6170,CABEZAL CARGADOR 220V XAEA OPTIMUM 5A 45w (USB...,18.0,73.80,197410.707600,267515.0,197500.0056,Cargador
139,CA6137,Cargador Cabezal Malibu Tipo C 30w PD769 Carga...,9.0,44.38,91246.258596,205623.0,91300.0000,Cargador
158,CA71103,CABEZAL PARA IPHONE 20W TIPO C MU7U2LL/A,8.0,120.96,233753.638400,193270.0,233900.0000,CABEZAL PARA IPHONE 20W TIPO C MU7U2LL/A
302,CA71117,CARGADOR CABEZAL SEND S01+ UN PUERTO USB 5v 3....,5.0,21.10,48974.446747,232127.0,49000.0004,Cargador
1050,IB-611,CARGADOR CABEZAL ADAPTADOR PUERTO USB + TYPE C...,1.0,3.63,8195.605023,225795.0,8200.0000,Cargador
1051,CA126,CARGADOR CABEZAL SAMSUNG 25W SUPER RAPIDA USB ...,1.0,3.42,15995.856164,467736.0,16000.0000,Cargador
1052,CA6169,CARGADOR CABEZAL SAMSUNG 65W SUPER RAPIDA / SA...,1.0,26.16,53968.346400,206322.0,54000.0000,Cargador
1053,CAR1502,CARGADOR CABEZAL SAMSUNG TURBO,1.0,2.09,8997.471100,430522.0,9000.0000,Cargador

In [225]:
#cambiar la categoria de ese producto a 'Cargador'
df.loc[df['Nombre del Producto'].str.contains('cabezal', case=False), 'Categoria'] = 'Cargador'

In [226]:
#ver cantidad de valores en la categoria
df['Categoria'].value_counts()

Categoria
Herramienta                                                             215
Modulo                                                                  125
Bateria                                                                 115
Auricular                                                               102
Vidrio Glass                                                             96
                                                                       ...
Antena Externa Adaptador Usb Wifi Placa Red Lan 802 N Gb                  1
SOPLADOR RL043A RELIFE                                                    1
Accesorio Disco                                                           1
BASTON SELFI STICK 3 GEN. QUALITY BLUETOOH 78 CM CON CABLE                1
Antena Tda 4k 5.0 Dbi Con Cable De 5 Mts Interior Y Exterior SG-3003      1
Name: count, Length: 75, dtype: int64

In [227]:
#ver valores con la cadena antena
df[df['Nombre del Producto'].str.contains('antena', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
270,CO953,PLACA USB/WIFI 150M CON ANTENA 5DBI DNW150U2,6.0,30.00,56766.850000,189233.0,56800.00000,Conectividad
387,CO949,EXTENSOR / REPETIDOR KANJI KJN-RP4200B 4 ANTENAS,4.0,52.72,101941.717753,193375.0,101999.99515,Conectividad
467,C8114,Antena Externa Adaptador Usb Wifi Placa Red La...,3.0,11.88,28485.641610,239799.0,28500.00000,Antena Externa Adaptador Usb Wifi Placa Red La...
569,CO952,PLACA USB/WIFI 150M CON ANTENA DN-W150U3 or 13...,3.0,15.00,28483.435900,189900.0,28500.01090,Conectividad
582,CO8132,ROUTER TP-LINK TL-WR850N WISP 2 ANTENAS 2.5DBI...,3.0,78.73,163413.009771,207572.0,163500.00960,Router
851,CO946,ROUTER DINAX WIFI 4 ANTENAS IEEE 802.11N DX-7R...,2.0,22.60,58972.650685,260962.0,59000.00000,Router
951,NG-Uw06,Adaptador Inalambrico Wifi Usb Red Noga NG-Uw0...,1.0,4.33,8995.216928,207752.0,9000.00400,Conectividad
1417,CO958,REPETIDOR WIFI 2 ANTENAS DINAX / REPRP4200C,1.0,14.81,26983.634950,182209.0,27000.00000,Conectividad
1418,CO8130,ROUTER TP-LINK ARCHER C50 AC1200 4 ANTENAS,1.0,29.00,64967.955000,224038.0,65000.00000,Router
1535,TV598,Antena Tda 4k 5.0 Dbi Con Cable De 5 Mts Inter...,0.0,0.00,0.000000,NaN,0.00000,Antena Tda 4k 5.0 Dbi Con Cable De 5 Mts Inter...

In [228]:
#ver valores que tengna estrictamente la cadena antena como primera caden a
df[df['Nombre del Producto'].str.contains('^antena', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
467,C8114,Antena Externa Adaptador Usb Wifi Placa Red La...,3.0,11.88,28485.64161,239799.0,28500.0,Antena Externa Adaptador Usb Wifi Placa Red La...
1535,TV598,Antena Tda 4k 5.0 Dbi Con Cable De 5 Mts Inter...,0.0,0.00,0.00000,NaN,0.0,Antena Tda 4k 5.0 Dbi Con Cable De 5 Mts Inter...

In [229]:
#cambiar la categoria de esos productos a 'Conectividad'
df.loc[df['Nombre del Producto'].str.contains('^antena', case=False), 'Categoria'] = 'Conectividad'

In [230]:
#cambiar la categoria de los productos con la cadena seña por arreglo a Servicio Tecnico
df.loc[df['Nombre del Producto'].str.contains('seña por arreglo', case=False), 'Categoria'] = 'Servicio Tecnico'

In [231]:
#ver valores con la cadena case disco
df[df['Nombre del Producto'].str.contains('case disco', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
376,D8211,CASE DISCO 3.0 Seisa Tranparente Dn-k209,4.0,16.2,31980.399658,197431.0,32000.0,Accesorio Disco

In [232]:
#a los valores con la cadena case disco 3.0 cambiar su categoria a Disco Interno
df.loc[df['Nombre del Producto'].str.contains('case disco 3.0', case=False), 'Categoria'] = 'Disco Interno'

In [233]:
#ver valores con la cadena soplador
df[df['Nombre del Producto'].str.contains('soplador', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
438,H9061,SOPLADOR RL043A RELIFE,4.0,11.96,21194.9884,177237.0,21209.46,SOPLADOR RL043A RELIFE

In [234]:
#cambiar la categoria de esos productos a 'Herramienta'
df.loc[df['Nombre del Producto'].str.contains('soplador', case=False), 'Categoria'] = 'Herramienta'

In [235]:
#ver valores con la cadena baston
df[df['Nombre del Producto'].str.contains('baston', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
292,A7217,BASTON SELFI STICK 3 GEN. QUALITY BLUETOOH 78 ...,5.0,15.7,33981.00742,216461.0,34000.0,BASTON SELFI STICK 3 GEN. QUALITY BLUETOOH 78 ...

In [236]:
#cambiar la categoria de esos productos a 'Accesorio'
df.loc[df['Nombre del Producto'].str.contains('baston', case=False), 'Categoria'] = 'Accesorio'

In [237]:
#ver fila con mas numero en su columna Cantidad
df[df['Cantidad'] == df['Cantidad'].max()]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
1554,NaN,nan,6294.0,166296.86,1.294925e+08,NaN,1.308388e+08,Joystick

In [238]:
#modificar la cattegoria de esa fila como : Sin Categoria
df.loc[df['Cantidad'] == df['Cantidad'].max(), 'Categoria'] = 'Sin Categoria'

In [239]:
#eliminar estas filas
df = df.dropna(subset=['Cantidad'])

In [240]:
#pasar a Int la columna Cantidad
df['Cantidad'] = df['Cantidad'].astype(int)

C:\Users\tm\AppData\Local\Temp\ipykernel_6980\985100368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cantidad'] = df['Cantidad'].astype(int)

In [241]:
#ver fila con el Nombre del Producto con mayor cantidad
df[df['Cantidad'] == df['Cantidad'].max()]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria
1554,NaN,nan,6294,166296.86,1.294925e+08,NaN,1.308388e+08,Sin Categoria

In [242]:
#redondear la columna ganancia a 0 decimales y transformar a int
df['Ganancia'] = df['Ganancia'].round(0)
df['Ganancia'] = df['Ganancia'].astype(int)

C:\Users\tm\AppData\Local\Temp\ipykernel_6980\1885528244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ganancia'] = df['Ganancia'].round(0)
C:\Users\tm\AppData\Local\Temp\ipykernel_6980\1885528244.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ganancia'] = df['Ganancia'].astype(int)

In [243]:
#Redondear ganancia prom. % a 5 decimales
df['Ganancia Prom. %'] = df['Ganancia prom. %'].round(5)

C:\Users\tm\AppData\Local\Temp\ipykernel_6980\1326243431.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ganancia Prom. %'] = df['Ganancia prom. %'].round(5)

In [244]:
#Redondear la columna 'Venta total' a 0 decimales y transformar a int
df['Venta total'] = df['Venta total'].round(0)
df['Venta total'] = df['Venta total'].astype(int)

C:\Users\tm\AppData\Local\Temp\ipykernel_6980\3970242243.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Venta total'] = df['Venta total'].round(0)
C:\Users\tm\AppData\Local\Temp\ipykernel_6980\3970242243.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Venta total'] = df['Venta total'].astype(int)

In [245]:
#ver valores con la cadena parlante y la cadena buzzer estrictamente
df[df['Nombre del Producto'].str.contains('parlante', case=False) & df['Nombre del Producto'].str.contains('buzzer', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria,Ganancia Prom. %
148,P106,Parlante Buzzer Altavoz MOTO G7 POWER / G7 PLA...,9,0.02,32800,1.640000e+08,32800,Parlante,1.640000e+08
1382,P105,Parlante Buzzer Altavoz GRAND PRIME,1,0.11,1000,9.089910e+05,1000,Parlante,9.089910e+05
1383,P129,Parlante Buzzer Altavoz MOTO G9 PLAY CAPSULA,1,1.29,19998,1.550290e+11,20000,Parlante,1.550290e+11
1384,P109,Parlante Buzzer Altavoz SAM A10/a20/a30/a40/a5...,1,0.46,2099,4.564220e+05,2100,Parlante,4.564220e+05
1385,P119,Parlante Buzzer Altavoz Sam A10s,1,0.57,2099,3.683210e+05,2100,Parlante,3.683210e+05

In [246]:
#cambiar la cateogira de ese producto a Repuesto Parlante
df.loc[df['Nombre del Producto'].str.contains('parlante', case=False) & df['Nombre del Producto'].str.contains('buzzer', case=False), 'Categoria'] = 'Repuesto Parlante Celular'

In [247]:
#ver valores con la cadena parlante
df[df['Nombre del Producto'].str.contains('parlante', case=False)]

,Código,Nombre del Producto,Cantidad,Costo total,Ganancia,Ganancia prom. %,Venta total,Categoria,Ganancia Prom. %
148,P106,Parlante Buzzer Altavoz MOTO G7 POWER / G7 PLA...,9,0.02,32800,1.640000e+08,32800,Repuesto Parlante Celular,1.640000e+08
331,PA131159,PARLANTE PORTATIL RADIO Y LECTOR TARJETA YX-07...,5,58.40,123929,2.122290e+05,124000,Parlante,2.122290e+05
391,CA6172,"FUENTE UNIVERSAL 9V 1,5A DOBLE FICHA ROUTER /...",4,8.80,25989,2.953550e+05,26000,Herramienta,2.953550e+05
572,PA6475,Parlante pc Genius Usb SP-Q180 AZUL,3,37.68,69954,1.856750e+05,70000,Parlante,1.856750e+05
573,PA6464,Parlantes Genius Sp Hf280 Usb 6w Wooden Madera,3,39.54,90952,2.194250e+05,86800,Parlante,2.194250e+05
815,PA27130,"PARLANTE BLUETOOTH DINAX DE 3"" REGGAE",2,12.31,41985,3.410860e+05,42000,Parlante,3.410860e+05
816,PA11821,PARLANTE DINAX 2.0 GAMER / BARRA DX-SPLITB C/LED,2,18.84,52977,2.812160e+05,53000,Parlante,2.812160e+05
817,PA645321,PARLANTE JBL BLUETOOTH GO3 BLUE,2,106.23,177471,1.670840e+05,177600,Parlante,1.670840e+05
818,PA131160,PARLANTE VELADOR BLUETOOTH CARGADOR INALAMBRIC...,2,43.32,77748,1.794940e+05,77800,Parlante,1.794940e+05
832,PA131142,Parlante JBL BLUETOOH FLIP 6 BLACK,2,199.80,429779,2.151150e+05,430000,Parlante,2.151150e+05
833,PA131141,Parlante JBL BLUETOOH FLIP 6 BLUE 2,2,195.90,421584,3.013400e+05,590520,Parlante,3.013400e+05
977,A6032,Auriculares Y Parlantes Bluetooth 2 En 1 West ...,1,14.82,43982,2.967960e+05,44000,Auricular,2.967960e+05
1324,PA27131,"PARLANTE BLUETOOTH DINAX DE 3"" ANKARA",1,7.53,11991,1.592630e+05,12000,Parlante,1.592630e+05
1325,PA6493,PARLANTE BT BLUETOOTH TG619 MP3 / BT / FM / AUX,1,10.42,28987,2.782110e+05,29000,Parlante,2.782110e+05
1326,PA6499,PARLANTE BT XIAOMI Mi PORTABLE 16W NEGRO,1,48.66,96941,1.992420e+05,97000,Parlante,1.992420e+05
1327,PA131153,PARLANTE Bluetooth GTS-1346 3'',1,4.91,11994,2.442990e+05,12000,Parlante,2.442990e+05
1328,PA64112,PARLANTE JBL BLUETOOTH Clip 4 Black,1,66.09,115920,1.754180e+05,116000,Parlante,1.754180e+05
1329,PA6486,"PARLANTE MULTIMEDIA RADIO 6,5"" NGL-400BT TWS/USB",1,15.82,44981,2.843500e+05,45000,Parlante,2.843500e+05
1330,PA64130,PARLANTE PHILCO - PARLANTE BT ROCK - SPH200R,1,11.93,15986,1.340160e+05,16000,Parlante,1.340160e+05
1331,PA6470,PARLANTES PC USB PAUSB62 DINAX,1,9.42,22989,3.051020e+05,28750,Parlante,3.051020e+05
1381,KTS-1687,Parlante Bt Radio iKaraoke box con microfono I...,1,34.19,54959,1.607660e+05,55000,Parlante,1.607660e+05
1382,P105,Parlante Buzzer Altavoz GRAND PRIME,1,0.11,1000,9.089910e+05,1000,Repuesto Parlante Celular,9.089910e+05
1383,P129,Parlante Buzzer Altavoz MOTO G9 PLAY CAPSULA,1,1.29,19998,1.550290e+11,20000,Repuesto Parlante Celular,1.550290e+11
1384,P109,Parlante Buzzer Altavoz SAM A10/a20/a30/a40/a5...,1,0.46,2099,4.564220e+05,2100,Repuesto Parlante Celular,4.564220e+05
1385,P119,Parlante Buzzer Altavoz Sam A10s,1,0.57,2099,3.683210e+05,2100,Repuesto Parlante Celular,3.683210e+05
1386,PA6479,Parlante Genius SP-HF500A 14W WOOD Madera 220V,1,28.25,85566,3.029090e+05,85600,Parlante,3.029090e+05
1387,PA131143,Parlante JBL BLUETOOH FLIP 5 CAMUFLADO,1,123.07,204851,1.664720e+05,205000,Parlante,1.664720e+05
1388,PA6483,Parlante JBL BLUETOOH FLIP 6 BLUE,1,97.95,214881,2.194000e+05,215000,Parlante,2.194000e+05
1389,PA64116,Parlante JBL Charge 5 Portatil Bluetooth Camuf...,1,158.22,359809,2.274310e+05,360000,Parlante,2.274310e+05
1390,PA64118,Parlante JBL Charge 5 Portatil Bluetooth Red,1,180.00,329782,1.832330e+05,330000,Parlante,1.832330e+05
1391,P6422,Parlante Portatil Bluetooth Speaker Bazooka Cu...,1,18.41,25978,1.411280e+05,26000,Parlante,1.411280e+05
1392,PA6476,Parlante pc Genius Usb SP-Q180 NARANJA,1,12.56,20985,1.670970e+05,21000,Parlante,1.670970e+05
1393,PA6477,Parlante pc Genius Usb SP-Q180 ROJO,1,12.56,20985,1.670970e+05,21000,Parlante,1.670970e+05
1394,PA642625,Parlantes 2.0 BT Noga AQUA 40w Pc Madera 4000PMPO,1,55.50,104933,1.890890e+05,105000,Parlante,1.890890e+05

In [248]:
#Eliminar la columna 'Ganancia prom. %'
df = df.drop(columns=['Ganancia prom. %'])

In [249]:
#guardar df como excel
df.to_excel('Reporte de ventas por articulos MOD 3.xlsx', index=False)